logging: DEBUG
# OpenAI API token
token: "~/.gpt/token.env"
# max number of retries to get a valid mission plan from ChatGPT
max_retries: 1
# schema per 1872.1-2024 + farm layout
log_directory: "./app/gpt_outputs/"
schema: "./app/resources/schema.xsd"
farm_layout: "./app/resources/reza_small.geojson"
# who to send this too?
host: 127.0.0.1
port: 12345