# log level
logging: DEBUG
# ROS2 node name
node_name: "husky_mission_planner"
service_name: "husky/mission_tasking"
# temp file log directory -> stores mission plans
log_directory: "./ros/.temp/"
# schema per 1872.1-2024 + farm layout
schema: "./app/resources/schema.xsd"
farm_layout: "./app/resources/reza_small.geojson"
# where to set the TCP server
host: 0.0.0.0
port: 12345